### ISSUE TITLE
problem in classification result

### ISSUE THREAD

**Issue by ahmadi219** [MEDEVIT/OSEA-4-Java#3]
I hope you answer my questions
1) Has this algorithm been improved and have you released a newer version of this algorithm?

2) Why does the algorithm sometimes analyze a beat and the result is that T_Off is placed before R_Peak and as a result, Missed Beat is detected in these places, even though it is wrong?

3) Can I select lead V to classify ?
Thanks

**Comment by col-panic** [comment]
Sorry, this program is not maintained, the original developer moved on to other tasks. Can't give you info on this. We will have to put this repo on archive.
